language: objective-c
osx_image: xcode10
sudo: false

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - xcodebuild [DEFAULT_OPTIONS] CODE_SIGNING_REQUIRED=NO

xcode_project: NintendoSwitchEshop.xcodeproj

matrix:
  include:
  - osx_image: xcode10
    env: SDK="iphonesimulator12.0" DESTINATION="name=iPhone XS,OS=12.0" SCHEME="NintendoSwitchEshop"
  - osx_image: xcode10
    env: SDK="iphonesimulator12.0" DESTINATION="name=iPhone XS,OS=12.0" SCHEME="NintendoSwitchEshopIntegrationTests"
  
# Upload our testing coverage to codecov.io.
after_success:
  - bash <(curl -s https://codecov.io/bash)