language: objective-c
osx_image: xcode10
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone XS

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

xcode_project: NintendoSwitchEshop.xcodeproj
xcode_scheme:
  - NintendoSwitchEshop
  - NintendoSwitchEshopIntegrationTests
  
# Upload our testing coverage to codecov.io.
after_success:
  - bash <(curl -s https://codecov.io/bash)